chipset = "sm8250"

[bootimg]
version = 2
base = 0x80000000
kernel = 0x8000
ramdisk = 0x1000000
second = 0x0
tags = 0x100
pagesize = 4096
dtb = 0x20000000

[[device]]
vendor = "samsung"
model = "galaxy_s20_fe"
variant = "r8q"
append = "console=ttyS0,115200n8"
bootimg = { version = 2, base = 0x80000000, kernel = 0x8000, ramdisk = 0x1000000, second = 0x0, tags = 0x100, pagesize = 4096, dtb = 0x20000000 }
