# Samsung S20FE R8Q SM8250 configuration

[bootimg]
base = 0x0
bootsize = 0x1f37000
kernel = 0x10008000
ramdisk = 0x12000000
second = 0x0
tags = 0x11e00000
pagesize = 4096

[[device]]
vendor = "samsung"
model = "sm8250"
append = "rootimg=/data/rootfs.img mobile.qcomsoc=qcom/sm8250 mobile.vendor=qcom mobile.model=r8q init=/sbin/init ro quiet splash"
