#!/bin/sh

set -e

case "${1}" in
	prereqs)
		exit 0
		;;
esac

for x in $(cat /proc/cmdline); do
	case $x in
		rootimg=*)
			ROOTIMG=${x#rootimg=}
			IMGPART=`echo ${ROOTIMG} | cut -d'/' -f2`
			;;
	esac
done

if [ -n "${IMGPART}" ]
then
	mkdir /${IMGPART}
	mount `blkid -t PARTLABEL=${IMGPART} -o device` /${IMGPART} || exit 0

	if [ -f "${ROOTIMG}" ]
	then
		losetup -f ${ROOTIMG}
	else
		umount /${IMGPART}
		rmdir /${IMGPART}
	fi
fi

