#!/bin/sh

# This script will run during init-premount and losetup rootfs image
# from any partition provided on `rootimg=` value in cmdline along
# with full path of the rootfs image file.
# Example:
#	In android perspective: if you've stored rootfs image in emmc
# path i.e. /sdcard/myrootfs.img then you can provide following
# cmdline value to boot the OS from the rootfs image:
# rootimg=PARTLABEL=userdata/media/0/myrootfs.img


set -e

case "${1}" in
	prereqs)
		exit 0
		;;
esac

for x in $(cat /proc/cmdline); do
	case $x in
		rootimg=*)
			ROOTIMG=${x#rootimg=}
			IMGPART=${ROOTIMG%%/*}
			IMGPATH=${ROOTIMG#*=}
			MNTDIR=${IMGPATH%%/*}
			;;
	esac
done

# Exit if empty
[ -z "${IMGPART}" ] && exit

# Find block device
if [ -b /dev/${IMGPART} ]
then
    DEVICE=/dev/${IMGPART}
elif blkid -t ${IMGPART} -o device > /dev/null
then
    DEVICE=`blkid -t ${IMGPART} -o device`
else
	exit
fi

# Mount and losetup the image file
mkdir -p ${MNTDIR}
mount ${DEVICE} ${MNTDIR}

if [ -f "${IMGPATH}" ]
then
	losetup -f ${IMGPATH}
else
	umount ${MNTDIR}
	rmdir ${MNTDIR}
fi
