name: Build Bootloader

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up jq
      run: sudo apt-get install -y jq

    - name: Set up tomlq
      run: sudo apt-get install -y python3-pip && pip3 install tomlq

    - name: Use mkbootimg from repository
      run: |
        chmod +x mkbootimg
        sudo cp mkbootimg /usr/local/bin/

    - name: Build bootloader
      run: |
        sudo chmod +x devices/qcom/bootloader.sh
        sudo ./devices/qcom/bootloader.sh sm8250

   # - name: Copy boot image to output directory
    #  run: cp /*.img /out

    - name: Upload boot image artifact
      uses: actions/upload-artifact@v4
      with:
        name: boot-image
        path: /path/to/output/directory/bootimg-galaxy_s20_fe-r8q
