name: Build Bootloader

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up jq
      run: sudo apt-get install -y jq

    - name: Set up tomlq
      run: sudo apt-get install -y python3-pip && pip3 install tomlq

    - name: Use mkbootimg from repository
      run: |
        chmod +x mkbootimg
        sudo cp mkbootimg /usr/local/bin/

    - name: Build bootloader
      run: |
        chmod +x devices/qcom/bootloader.sh
        ./devices/qcom/bootloader.sh sm8250
