name: Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Shell environment
      run: sudo apt-get update

    - name: Build
      run: sudo ./build.sh -t sm8250 -s -r
        
        echo "Building the project..."
